artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Sibasis555/Face_mask_detection/raw/main/datasets/dummy_bird_species.zip
  local_data_file: artifacts/data_ingestion/dummy_bird_species.zip
  unzip_dir: artifacts/data_ingestion
  # train_data_path: artifacts/data_ingestion/trainingSet
  # val_data_path: artifacts/data_ingestion/valSet



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pth
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.pth




prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.pth




training:
  train_data: artifacts/data_ingestion/dummy_bird_species/Train
  test_data: artifacts/data_ingestion/dummy_bird_species/Test
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pth