stages:
  data_ingestion:
    cmd: python src/bird_classification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/bird_classification/pipeline/stage_01_data_ingestion.py
      - src/bird_classification/utils/config.yaml
    outs:
      - artifacts/data_ingestion/dummy_bird_species


  prepare_base_model:
    cmd: python src/bird_classification/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/bird_classification/pipeline/stage_02_prepare_base_model.py
      - src/bird_classification/utils/config.yaml
    params:
      - CLASSES
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/bird_classification/pipeline/stage_03_model_training.py
    deps:
      - src/bird_classification/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/dummy_bird_species/Train
      - artifacts/data_ingestion/dummy_bird_species/Test
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - LEARNING_RATE
      - MOMENTUM
    outs:
      - artifacts/training/model.h5
